### ISSUE TITLE
nuxi generate - Unexpected token in composition API support files of nuxt-bridge

### ISSUE THREAD

**Issue by fabifink** [nuxt/bridge#365] opened 2022-06-03 19:28 UTC
### Environment

Nuxt project info:                                                                                                                                                            21:27:04

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `bridge`, `ssr`, `target`, `head`, `css`, `plugins`, `components`, `buildModules`, `modules`, `io`, `axios`, `auth`, `build`, `router`, `elementUI`, `purgeCSS`, `typescript`, `i18n`
- Runtime Modules:  `@nuxtjs/axios@5.13.6`, `@nuxtjs/auth-next@5.0.0-1617968180.f699074`, `nuxt-socket-io@1.1.24`, `nuxt-element-ui@1.0.10`, `nuxt-i18n@6.28.1`
- Build Modules:    `@nuxtjs/stylelint-module@4.1.0`, `@nuxtjs/tailwindcss@4.2.1`, `@nuxt/postcss8@1.1.3`, `@nuxt/bridge@3.0.0-27566698.2b0045e`
------------------------------

### Reproduction

-

### Describe the bug

I have migrated my Nuxt2 application to Nuxt-Bridge and if I run `nuxi dev` everything is working fine. But once I try to build the applications (static target) with `nuxi generate`, I get the following error:

```

ERROR in ./node_modules/@nuxt/bridge/dist/runtime/app.plugin.mjs 102:59
Module parse failed: Unexpected token (102:59)
File was processed with these loaders:
 * ./node_modules/unplugin/dist/webpack/loaders/transform.js
You may need an additional loader to handle the result of these loaders.
|     get (target, prop) {
|       if (prop[0] === '$') {
>         return target.nuxt2Context[prop] || target.vue2App?.[prop]
|       }
|       return Reflect.get(target, prop)
 @ ./.nuxt/index.js 48:0-76 375:25-55 381:19-49
 @ ./.nuxt/client.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./node_modules/@nuxt/bridge/dist/runtime/capi.plugin.mjs ./.nuxt/client.js

ERROR in ./node_modules/@nuxt/bridge/dist/runtime/composables.mjs 27:27
Module parse failed: Unexpected token (27:27)
File was processed with these loaders:
 * ./node_modules/unplugin/dist/webpack/loaders/transform.js
You may need an additional loader to handle the result of these loaders.
|         return target.public;
|       }
>       return target[prop] ?? target.public[prop];
|     },
|     set(target, prop, value) {
 @ ./node_modules/@nuxt/bridge/dist/runtime/app.mjs 1:0-72 4:35-50 29:13-31
 @ ./node_modules/@nuxt/bridge/dist/runtime/index.mjs
 @ ./node_modules/@nuxt/bridge/dist/runtime/capi.plugin.mjs
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./node_modules/@nuxt/bridge/dist/runtime/capi.plugin.mjs ./.nuxt/client.js
```

If I deactivate composition API support in the nuxt.config.js, the error disappears, but I am then unable to use the composition API (Which is one of the main reasons for me to migrate). 

Can you give me any hint on what I might be doing wrong here?

**Comment by fabifink** [comment] 2022-06-03 19:39
fyi: Error happens with vite, as well as wepback4 as a bundler.

**Comment by danielroe** [comment] 2022-07-03 14:59
Would you provide a minimal reproduction please? 🙏

**Comment by MartinX3** [comment] 2022-07-07 00:16
@danielroe here is the minimal example.
It happens if I use `export default defineNuxtConfig(` in `nuxt.config.js`

[codesandbox-nuxt-master.zip](https://github.com/nuxt/bridge/files/9059330/codesandbox-nuxt-master.zip)

**Comment by dargmuesli** [comment] 2022-07-07 09:17
For me the workaround to add `@nuxt/bridge` to the `transpile` array works, but I'm not sure if this is the way to go.

**Comment by danielroe** [comment] 2022-07-07 09:18
Yes, `@nuxt/bridge` should be transpiled. (In fact, it should add itself to that array, so let's see what's going wrong there.)

**Comment by MartinX3** [comment] 2022-07-07 09:20
You mean
```
    build: {
        transpile: ['@nuxt/bridge'],
    },
```
?

That still results in
`[nitro] Please use nuxt generate for static target`

**Comment by dargmuesli** [comment] 2022-07-07 09:20
After https://github.com/nuxt/bridge/pull/324 it should not show that warning anymore.

**Comment by MartinX3** [comment] 2022-07-07 09:21
At the ent it also tells me `✔ You can now deploy .output/public to any static hosting! `
But there is no `.output/public`
Even no `.output`.

**Comment by dargmuesli** [comment] 2022-07-07 09:27
> But there is no `.output`

This will be fixed by https://github.com/nuxt/bridge/pull/324 too.

**Comment by MartinX3** [comment] 2022-07-07 09:28
That's great!
Maybe #365 and #27 should get added to the linked issues in this PR if they get fixed by it.

**Comment by danielroe** [comment] 2022-07-09 15:12
I cannot reproduce on the latest version of Nuxt Bridge with the zipfile linked by @MartinX3 above.

If you are still experiencing this, would you let me know and provide a minimal reproduction? 🙏

**Closed by danielroe** 2022-07-09 15:12 UTC
Labels: needs reproduction, pending triage
