### ISSUE TITLE
Lack of context typing with `useNuxtApp`

### ISSUE THREAD

**Issue by thisismydesign** [nuxt/bridge#539] opened 2022-09-16 12:37 UTC
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.17.0`
- Nuxt Version:     `2.16.0-27616340.013f051b`
- Nitro Version:    `0.4.24`
- Package Manager:  `yarn@1.22.19`
- Builder:          `webpack`
- User Config:      `server`, `head`, `css`, `env`, `plugins`, `components`, `modules`, `apollo`, `feed`, `build`, `alias`, `transpileDependencies`, `i18n`, `sitemap`, `auth`, `typescript`, `serverHandlers`, `devServerHandlers`, `bridge`, `buildModules`
- Runtime Modules:  `@nuxtjs/axios@5.13.6`, `@nuxtjs/auth@4.9.1`, `@nuxtjs/apollo@4.0.1-rc.5`, `@nuxtjs/feed@2.0.0`, `@nuxtjs/sitemap@2.4.0`, `@nuxtjs/i18n@7.3.0`, `nuxt-rollbar-module@1.1.0`
- Build Modules:    `()`, `@nuxt/bridge@3.0.0-27700335.6dfc006`

### Reproduction

`const { $auth } = useNuxtApp()` gives `any` type, whereas `nuxt2Context.$auth` from `const { nuxt2Context } = useNuxtApp()` is typed correctly.

### Describe the bug

Lack of typing

### Additional context

Perhaps related to https://github.com/nuxt/bridge/issues/130

**Comment by antlionguard** [comment] 2022-09-16 19:48
I think duplicate of this #465

**Comment by valh1996** [comment] 2022-10-05 15:07
Same problem for me, as a workaround, I use :
```
const { nuxt2Context: { $repository, $toast, $i18n } } = useNuxtApp()
```

**Comment by wattanx** [comment] 2023-04-23 06:33
I believe this issue has been resolved at https://github.com/nuxt/bridge/issues/130.
You can extend `NuxtAppCompat` to add types such as `$auth`.

**Closed** 2023-04-25 14:34 UTC
Labels: bug, types
