### ISSUE TITLE
Upgrade to latest `unplugin`

### ISSUE THREAD

**Issue by danielroe** [nuxt/bridge#460] opened 2022-08-03 17:52 UTC
Looks like there might be a regression in `unplugin`.

I'm getting the following error logs when building locally `TEST_WITH_WEBPACK=1 yarn nuxi build playground`:

```bash
ERROR in ./playground/components/FetchTest.vue?vue&type=template&id=7a38cfc8&
Module not found: Error: Can't find options with ident 'nuxt:auto-imports-transform'
 @ ./playground/components/FetchTest.vue?vue&type=template&id=7a38cfc8& 1:0-402 1:0-402
 @ ./playground/components/FetchTest.vue
 @ ./playground/pages/legacy-capi.vue
 @ ./playground/.nuxt/router.js
 @ ./playground/.nuxt/index.js
 @ ./playground/.nuxt/client.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./playground/.nuxt/client.js
```

Possibly related: https://github.com/webpack/webpack/issues/8952.

_Originally posted by @danielroe in https://github.com/nuxt/bridge/issues/435#issuecomment-1199583257_

**Comment by antfu** [comment] 2022-08-03 18:20
Also related to https://github.com/webpack/webpack/issues/8406

Seems to be fixed in Webpack 5, I will see want I can workaround it with webpack 4 in unplugin

**Comment by antfu** [comment] 2022-08-03 19:20
I have set up the test against Webpack 4 but does not hit this error:
https://github.com/unjs/unplugin/runs/7659282481?check_suite_focus=true#step:9:39

Might need some help to reproduce it

**Closed** 2022-08-04 08:18 UTC
