### ISSUE TITLE
Static dir on windows

### ISSUE THREAD

**Issue by stephenjason89** [nuxt/bridge#325] opened 2022-05-01 13:04 UTC
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v14.17.0`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `yarn@1.22.17`
- Builder:          `webpack`
- User Config:      `srcDir`, `ssr`, `dev`, `alias`, `image`, `generate`, `head`, `typescript`, `publicRuntimeConfig`, `privateRuntimeConfig`, `css`, `loading`, `loadingIndicator`, `plugins`, `components`, `buildModules`, `modules`, `apollo`, `proxy`, `axios`, `vuetify`, `build`, `bridge`
- Runtime Modules:  `@nuxt/image@0.6.2`, `@nuxtjs/axios@5.13.6`, `@nuxtjs/apollo@4.0.1-rc.5`, `@nuxtjs/proxy@2.1.0`, `nuxt-social-meta@1.0.0`
- Build Modules:    `nuxt-storm@1.1.3`, `@nuxtjs/router@1.7.0`, `nuxt-compress@5.0.0`, `@nuxtjs/vuetify@1.12.3`, `@nuxt/bridge@3.0.0-27495135.4d1a6ba`
------------------------------

### Reproduction

![image](https://user-images.githubusercontent.com/3810177/166147118-80fd28a8-bbae-4fba-9731-d7a5ff531c94.png)

### Describe the bug

Everything in my static/icons dir is not found only on windows OS

Mac OS works fine

**Comment by danielroe** [comment] 2022-05-01 13:09
duplicate of https://github.com/nuxt/bridge/issues/312. should be resolved by https://github.com/nuxt/bridge/pull/316.

**Comment by stephenjason89** [comment] 2022-05-02 04:47
@danielroe Hello I was certain that it was working before. But with the newer bridge installed, it's not working as well.
Throwing other errors now too.

**Comment by danielroe** [comment] 2022-07-03 15:02
This should be resolved in https://github.com/nuxt/bridge/pull/316 - let me know if not and we can reopen.

**Closed by danielroe** 2022-07-03 15:02 UTC
Labels: pending triage
