### ISSUE TITLE
useRuntimeConfig is getting undefined after nuxt-edge update to the latest version.

### ISSUE THREAD

**Issue by Envoy49** [nuxt/bridge#522] opened 2022-09-08 06:29 UTC
### Discussed in https://github.com/nuxt/bridge/discussions/521

<div type='discussions-op-text'>

<sup>Originally posted by **Envoy49** September  8, 2022</sup>
Hi @danielroe, I've updated my nuxt-edge version to the latest and it took me a lot to understand that after update my `useRuntimeConfig` variables gets undefined on server side as a reason crashing the app.
I hardcoded env values, then app worked.

So I went from this version  `"nuxt-edge": "^2.16.0-27358576.777a4b7f"` to this  `"nuxt-edge": "^2.16.0-27708500.54e852f"` in order to solve this bug -------> https://github.com/nuxt/bridge/issues/453 which has been fixed recently

I am wondering if there were any breaking changes between versions that could lead to this issue?</div>

This is my yarn.lock file difference. Can @nuxt/config-edge be a reason for this beahviour?
![Screen Shot 2022-09-09 at 11 16 17 am](https://user-images.githubusercontent.com/94023356/189252052-7ab55a07-b94d-47e3-945f-85c25844f179.png)

**Comment by joel-wenzel** [comment] 2022-09-09 18:27
Duplicate of this one it seems like: https://github.com/nuxt/bridge/issues/508

**Comment by Envoy49** [comment] 2022-09-10 07:22
> Duplicate of this one it seems like: #508

Yes sorry, I was searching useRuntimeConfig in open issues. Can this stay open as well or merged with yours?

**Comment by Envoy49** [comment] 2022-09-15 00:08
@danielroe Could you please have a look to these issues when you get a chance?

**Comment by danielroe** [comment] 2022-09-15 09:31
Let's track in https://github.com/nuxt/bridge/issues/508.

**Closed by danielroe** 2022-09-15 09:31 UTC
