### ISSUE TITLE
Nuxt-bridge useNuxtApp() not available inside middleware

### ISSUE THREAD

**Issue by stephenjason89** [nuxt/bridge#436] opened 2022-07-21 16:17 UTC
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.0`
- Nuxt Version:     `2.16.0-27616340.013f051b`
- Package Manager:  `yarn@3.2.1`
- Builder:          `webpack`
- User Config:      `srcDir`, `bridge`, `ssr`, `dev`, `webpackOptimisations`, `alias`, `image`, `generate`, `head`, `typescript`, `publicRuntimeConfig`, `privateRuntimeConfig`, `css`, `loading`, `loadingIndicator`, `plugins`, `components`, `buildModules`, `modules`, `proxy`, `axios`, `vuetify`, `build`, `serverHandlers`, `devServerHandlers`
- Runtime Modules:  `@nuxtjs/vuetify@1.12.3`, `@nuxt/image@0.6.2`, `@nuxtjs/axios@5.13.6`, `@nuxtjs/proxy@2.1.0`, `nuxt-social-meta@1.0.0`
- Build Modules:    `()`, `nuxt-storm@1.1.3`, `nuxt-compress@5.0.0`, `nuxt-webpack-optimisations@2.2.4`, `@pinia/nuxt@0.3.0`, `@nuxt/bridge@3.0.0-27636329.42ea75b`
------------------------------

### Reproduction

<img width="569" alt="image" src="https://user-images.githubusercontent.com/3810177/180263410-a5b8ca83-91f7-4f42-8525-b6067276af0f.png">

### Describe the bug

useNuxtApp() inside a middleware fails with an error
<img width="569" alt="image" src="https://user-images.githubusercontent.com/3810177/180263465-ca6a719b-3aaf-4751-b858-a5fb101f0c8b.png">

**Comment by antlionguard** [comment] 2022-07-22 16:15
Can you share minimal reproduction? Or middleware code?

**Comment by stephenjason89** [comment] 2022-07-23 18:32
@antlionguard will provide one tomorrow. Is useNuxtApp working for you inside the middleware on nuxt-bridge?

**Comment by antlionguard** [comment] 2022-07-23 18:34
> @antlionguard will provide one tomorrow. Is useNuxtApp working for you inside the middleware on nuxt-bridge?

Yes it’s works at my project.

**Comment by stephenjason89** [comment] 2022-07-23 18:42
Hello @antlionguard 
here is a repro
https://github.com/stephenjason89/nuxt-bridge

**Comment by antlionguard** [comment] 2022-07-23 19:01
i think @danielroe should look at this

**Comment by stephenjason89** [comment] 2022-07-24 07:34
Thank you @antlionguard & @danielroe

**Comment by danielroe** [comment] 2022-07-25 12:24
Seems to be working: https://stackblitz.com/github/stephenjason89/nuxt-bridge

**Comment by stephenjason89** [comment] 2022-07-25 17:18
That's weird. I'll try again.

**Comment by stephenjason89** [comment] 2022-07-25 17:37
Hello @danielroe I have tried cloning the repo again,
yarn install then yarn run dev but still getting the error.

Then i tried npm just like in stackblitz just to be sure.
But still getting the error.

**Comment by antlionguard** [comment] 2022-07-25 17:52
> Hello @danielroe I have tried cloning the repo again, yarn install then yarn run dev but still getting the error.
> 
> Then i tried npm just like in stackblitz just to be sure. But still getting the error.
> 
> This is the line that throws the error <img alt="image" width="1012" src="https://user-images.githubusercontent.com/3810177/180840111-3160b54c-b51d-48e8-a2e0-cc3b2623d425.png">

You should try remove yarn lock and install all packages again

**Comment by stephenjason89** [comment] 2022-07-26 05:25
@antlionguard I just tried to remove yarn.lock now and yarn install.
Same thing is happening for me.

here are the console errors
<img width="992" alt="image" src="https://user-images.githubusercontent.com/3810177/180929710-b5901c61-2519-4dd9-9855-c6d874484347.png">
<img width="961" alt="image" src="https://user-images.githubusercontent.com/3810177/180929818-91e38dd6-1b7f-4351-a6bb-4dcb39706557.png">

**Comment by stephenjason89** [comment] 2022-08-27 14:51
@Luferov yeah, let's wait and hope for a fix.

**Comment by stephenjason89** [comment] 2022-08-27 15:17
@danielroe 
I updated the reproduction to show the errors


I forgot to include my env file which makes my ssr variable true

so i just changed it here
<img width="482" alt="image" src="https://user-images.githubusercontent.com/3810177/187036331-56ce95e4-5de3-441f-8c07-41559def7fe7.png">


Latest nuxt-bridge causes more bugs.
Every js seems to not work.
It just renders the html

please see readme

**Comment by Luferov** [comment] 2022-09-14 19:30
> @danielroe I updated the reproduction to show the errors
> 
> I forgot to include my env file which makes my ssr variable true
> 
> so i just changed it here <img alt="image" width="482" src="https://user-images.githubusercontent.com/3810177/187036331-56ce95e4-5de3-441f-8c07-41559def7fe7.png">
> 
> Latest nuxt-bridge causes more bugs. Every js seems to not work. It just renders the html
> 
> please see readme


unfortunately if ssr: false then also doesn't work ☹️

**Comment by wattanx** [comment] 2024-01-06 07:25
It has not responded for a while, so I am closing it.
Reopen is welcome.
(It would be helpful if you could provide a reproduction)

**Closed by wattanx** 2024-01-06 07:25 UTC
Labels: needs reproduction, pending triage
