### ISSUE TITLE
During page reload, css styles seems to be loaded last in Nuxt Bridge but working correctly in Nuxt 3

### ISSUE THREAD

**Issue by azelalynetan** [nuxt/bridge#487] opened 2022-08-15 04:14 UTC
### Environment

Node Version: v16.16.4
Nuxt Version: Nuxt-Edge Latest
Nuxt Bridge: 3.0.0-27657000
Package Manager: npm
Bundler: Webpack

### Reproduction

1. Created a nuxt 2 app and upgraded it to Nuxt bridge.
2. Installed Tailwind as described in the [docs](https://tailwindcss.com/docs/guides/nuxtjs).
3. CSS Styles are not loading for a second after refresh.
![NuxtBridgeCSSIssue](https://user-images.githubusercontent.com/29948566/184575902-9c6bd737-e98b-48fb-b3b2-62ef34d8adcf.gif)

### Describe the bug

When page reload, css styles are not loading for a second in Nuxt Bridge but I have tried it out using Nuxt3 and it's working correctly.

**Comment by AndrewBogdanovTSS** [comment] 2022-09-13 08:00
@azelalynetan provide a reproduction at https://stackblitz.com/
@danielroe looks like a duplicate of https://github.com/windicss/nuxt-windicss/issues/159

**Closed** 2022-09-15 09:32 UTC
Labels: pending triage
