### ISSUE TITLE
css styles not applied after building

### ISSUE THREAD

**Issue by alih70442** [nuxt/bridge#561] opened 2022-09-27 17:56 UTC
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.17.0`
- Nuxt Version:     `2.16.0-27720022.54e852f`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `bridge`, `vite`, `css`, `plugins`, `components`, `buildModules`, `modules`, `pwa`, `build`, `serverHandlers`, `devServerHandlers`
- Runtime Modules:  `-`
- Build Modules:    `()`, `@nuxt/bridge@3.0.0-27737014.fcf636d`

### Reproduction

https://stackblitz.com/edit/nuxt-starter-y8k5hw?file=nuxt.config.js

### Describe the bug

in dev mode, all styles from `nuxt.config.js` > `css` applied as well.
after building the project, css files not loaded.

### Additional context

this bug appears after `3.0.0-27736739.990b28d` version released.

**Comment by goncharof** [comment] 2022-10-10 18:37
also pwa and icon modules don't work at all

**Comment by IlyaSemenov** [comment] 2022-11-01 10:03
The manifest at `.output/server/chunks/app/client.manifest.mjs` is not generated correctly, entry-legacy css array is empty.

**Comment by IlyaSemenov** [comment] 2022-11-01 12:42
FWIW, I managed to fix the problem by the following pnpm patch `patches/vite@3.1.8.patch`:

```patch
diff --git a/dist/node/chunks/dep-4da11a5e.js b/dist/node/chunks/dep-4da11a5e.js
index ef2d5d810506e20169239232d9972f1adf9bcdd8..114693e1473f068b95f016efa096ddf992521413 100644
--- a/dist/node/chunks/dep-4da11a5e.js
+++ b/dist/node/chunks/dep-4da11a5e.js
@@ -44284,7 +44284,7 @@ function cssPostPlugin(config) {
                     // this is a shared CSS-only chunk that is empty.
                     pureCssChunks.add(chunk.fileName);
                 }
-                if (opts.format === 'es' || opts.format === 'cjs') {
+                if (opts.format === 'es' || opts.format === 'cjs' || opts.format === 'system') {
                     const cssAssetName = chunk.facadeModuleId
                         ? normalizePath$3(path$n.relative(config.root, chunk.facadeModuleId))
                         : chunk.name;
```

With that, `@vite/plugin-legacy` starts injecting CSS into legacy chunks, which then makes its way into Nuxt/Nitro SSR bundle. I am not sure if that is a valid approach at all - it just happens to work.

If someone has time to come up with a minimal reproduction repo, please open an upstream issue.

**Comment by IlyaSemenov** [comment] 2022-11-07 05:51
I suspect the actual fix would be serving modern format scripts in addition to legacy (#15), and pull css information from modern format chunks.

**Comment by IlyaSemenov** [comment] 2022-11-08 06:21
Note that upgrading vite to 3.2.x makes it work (thanks to https://github.com/vitejs/vite/pull/10496), however it leads to FOUC because styles are inlined rather than injected via `<link rel="stylesheet">`. The patch above delivers better result.

**Comment by maxarias-io** [comment] 2022-12-01 17:59
Any news on this one? Running a new nuxt 2 + bridge build, it seems that global css styles aren't applied

**Comment by AndreyYolkin** [comment] 2022-12-05 15:37
> Any news on this one? Running a new nuxt 2 + bridge build, it seems that global css styles aren't applied

https://github.com/nuxt/bridge/issues/561#issuecomment-1298454739 helps both with 3.1.x and 3.2.x

**Comment by wattanx** [comment] 2023-11-03 15:07
Is this still occurring? If so, please provide a reproduction 🙏

**Comment by AndreyYolkin** [comment] 2023-11-08 13:17
> Is this still occurring? If so, please provide a reproduction 🙏
### Repo: 
https://github.com/AndreyYolkin/bridge-missing-css

### Dev:
<img width="450" alt="image" src="https://github.com/nuxt/bridge/assets/11289484/5800644a-fbad-4227-9b7b-fd2f2c30a836">

### Prod:
<img width="544" alt="image" src="https://github.com/nuxt/bridge/assets/11289484/9d12c260-2b0e-4982-8ac7-39a54903d1db">

### Output:
<img width="408" alt="image" src="https://github.com/nuxt/bridge/assets/11289484/4a87e6ae-3c17-4220-9040-7f82d381bbe9">

**Comment by wattanx** [comment] 2024-04-04 13:34
Resolved by https://github.com/nuxt/bridge/pull/1164
If you want to use it quickly, you can use `@nuxt/bridge-edge@3.1.0-28536231.051ed68`.

https://stackblitz.com/edit/github-yueotr

**Closed by wattanx** 2024-04-04 13:34 UTC
Labels: needs reproduction
