### ISSUE TITLE
Error with VITE and SSR turned off

### ISSUE THREAD

**Issue by vsanrocha** [nuxt/bridge#686] opened 2023-01-18 16:35 UTC
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `2.16.0-27720022.54e852f`
- Nitro Version:    `1.0.0`
- Package Manager:  `pnpm@7.13.6`
- Builder:          `vite`
- User Config:      `ssr`, `components`, `bridge`, `serverHandlers`, `devServerHandlers`, `devServer`, `typescript`, `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `()`, `@nuxt/bridge@3.0.0-27889410.9247608`
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-bridge-test-54d1qd

### Describe the bug

Whe we run `pnpm dev`  it doesn't show any error in the terminal, but in the browser it goes blank and shows this error in `conole.log`:

```
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
```

**Comment by cstrlc** [comment] 2023-01-19 02:04
Possible duplicate of #569

**Comment by cmoeser** [comment] 2023-01-19 20:30
same issue

**Closed** 2023-05-16 22:21 UTC
Labels: pending triage
