### ISSUE TITLE
Nuxt Bridge + vueuse/head - Cannot start nuxt:  Cannot find module 'nuxt'  

### ISSUE THREAD

**Issue by max5432112345** [nuxt/bridge#444] opened 2022-07-27 15:09 UTC
### Environment

- Operating System: `Linux`
- Node Version:     `v16.16.0`
- Nuxt Version:     `2.16.0-27616340.013f051b`
- Package Manager:  `npm@8.11.0`
- Builder:          `webpack`
- User Config:      `target`, `head`, `css`, `components`, `buildModules`, `build`, `bridge`, `serverHandlers`, `devServerHandlers`
- Runtime Modules:  `-`
- Build Modules:    `()`, `@pinia/nuxt@0.3.1`, `@nuxt/bridge@3.0.0-27639120.e7a7f9b`

### Reproduction

Install https://github.com/piniajs/example-nuxt-bridge
Install npm install --save @vueuse/head
Set   bridge: { meta: true }

### Describe the bug

Cannot start nuxt:  Cannot find module 'nuxt'  

### Additional context

After reinstall 

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: pinia-example-nuxt@1.0.0
npm ERR! Found: vue@3.2.37
npm ERR! node_modules/vue
npm ERR!   peerOptional vue@"^2.6.0 || ^3.2.0" from @vueuse/core@8.9.4
npm ERR!   node_modules/@vueuse/core
npm ERR!     @vueuse/core@"^8.9.4" from the root project
npm ERR!   peer vue@">=3" from @vueuse/head@0.7.7
npm ERR!   node_modules/@vueuse/head
npm ERR!     @vueuse/head@"^0.7.7" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! pinia@"^2.0.16" from the root project
```

**Comment by danielroe** [comment] 2022-07-28 10:15
These are package management issues and can probably be addressed by using yarn or npm overrides. In general, however, I would advise against using the (experimental) `@vueuse/head` implementation on Bridge.

**Comment by antlionguard** [comment] 2022-07-28 10:48
This reproduction uses [3.0.0-27621666.ee600b4](https://www.npmjs.com/package/@nuxt/bridge-edge/v/3.0.0-27621666.ee600b4) Can you try with a newer version of bridge? [3.0.0-27639120.e7a7f9b](https://www.npmjs.com/package/@nuxt/bridge-edge/v/3.0.0-27639120.e7a7f9b)

**Comment by max5432112345** [comment] 2022-07-28 11:25
> These are package management issues and can probably be addressed by using yarn or npm overrides. In general, however, I would advise against using the (experimental) `@vueuse/head` implementation on Bridge.

> notably that useAsyncData and useFetch composables are not available
with bridge no [Directly calling an API Endpoint](https://v3.nuxtjs.org/guide/features/data-fetching/#directly-calling-an-api-endpoint) ?

**Comment by max5432112345** [comment] 2022-07-28 11:27
> This reproduction uses [3.0.0-27621666.ee600b4](https://www.npmjs.com/package/@nuxt/bridge-edge/v/3.0.0-27621666.ee600b4) version of nuxt-bridge. Can you try with a newer version of bridge? [3.0.0-27639120.e7a7f9b](https://www.npmjs.com/package/@nuxt/bridge-edge/v/3.0.0-27639120.e7a7f9b)

how to do that?
in package.json is `@nuxt/bridge": "npm:@nuxt/bridge-edge`

**Comment by antlionguard** [comment] 2022-07-28 11:28
> > This reproduction uses [3.0.0-27621666.ee600b4](https://www.npmjs.com/package/@nuxt/bridge-edge/v/3.0.0-27621666.ee600b4) version of nuxt-bridge. Can you try with a newer version of bridge? [3.0.0-27639120.e7a7f9b](https://www.npmjs.com/package/@nuxt/bridge-edge/v/3.0.0-27639120.e7a7f9b)
> 
> how to do that? in package.json is `@nuxt/bridge": "npm:@nuxt/bridge-edge`

You can remove `yarn.lock` and run `yarn install`.

**Comment by max5432112345** [comment] 2022-07-28 11:30
> > > This reproduction uses [3.0.0-27621666.ee600b4](https://www.npmjs.com/package/@nuxt/bridge-edge/v/3.0.0-27621666.ee600b4) version of nuxt-bridge. Can you try with a newer version of bridge? [3.0.0-27639120.e7a7f9b](https://www.npmjs.com/package/@nuxt/bridge-edge/v/3.0.0-27639120.e7a7f9b)
> > 
> > 
> > how to do that? in package.json is `@nuxt/bridge": "npm:@nuxt/bridge-edge`
> 
> You can remove `yarn.lock` and run `yarn install`.

I think i always do so. i use npm

**Comment by antlionguard** [comment] 2022-07-28 11:32
> > > > This reproduction uses [3.0.0-27621666.ee600b4](https://www.npmjs.com/package/@nuxt/bridge-edge/v/3.0.0-27621666.ee600b4) version of nuxt-bridge. Can you try with a newer version of bridge? [3.0.0-27639120.e7a7f9b](https://www.npmjs.com/package/@nuxt/bridge-edge/v/3.0.0-27639120.e7a7f9b)
> > > 
> > > 
> > > how to do that? in package.json is `@nuxt/bridge": "npm:@nuxt/bridge-edge`
> > 
> > 
> > You can remove `yarn.lock` and run `yarn install`.
> 
> I think i always do so. i use npm

in that case you should remove package.lock and run npm install.

**Comment by max5432112345** [comment] 2022-07-28 11:35
> > > > > This reproduction uses [3.0.0-27621666.ee600b4](https://www.npmjs.com/package/@nuxt/bridge-edge/v/3.0.0-27621666.ee600b4) version of nuxt-bridge. Can you try with a newer version of bridge? [3.0.0-27639120.e7a7f9b](https://www.npmjs.com/package/@nuxt/bridge-edge/v/3.0.0-27639120.e7a7f9b)
> > > > 
> > > > 
> > > > how to do that? in package.json is `@nuxt/bridge": "npm:@nuxt/bridge-edge`
> > > 
> > > 
> > > You can remove `yarn.lock` and run `yarn install`.
> > 
> > 
> > I think i always do so. i use npm
> 
> in that case you should remove package.lock and run npm install.

i understand, and do that yesterday and today but that not help
```
{
  "name": "pinia-example-nuxt",
  "version": "1.0.0",
  "private": true,
  "license": "MIT",
  "scripts": {
    "dev": "nuxi dev",
    "build": "nuxi build",
    "start": "node .output/server/index.mjs",
    "generate": "nuxi generate"
  },
  "dependencies": {
    "@pinia/nuxt": "^0.3.1",
    "@vueuse/core": "^9.0.0",
     "@vueuse/head": "^0.7.7",
    "nuxt-edge": "latest",
    "pinia": "^2.0.17"
  },
  "devDependencies": {
    "@nuxt/bridge": "npm:@nuxt/bridge-edge",
    "@nuxt/types": "^2.15.8",
    "prettier": "^2.7.1"
  }
}
```

**Comment by max5432112345** [comment] 2022-07-28 11:46
> > > This reproduction uses [3.0.0-27621666.ee600b4](https://www.npmjs.com/package/@nuxt/bridge-edge/v/3.0.0-27621666.ee600b4) version of nuxt-bridge. Can you try with a newer version of bridge? [3.0.0-27639120.e7a7f9b](https://www.npmjs.com/package/@nuxt/bridge-edge/v/3.0.0-27639120.e7a7f9b)
> > 
> > 
> > how to do that? in package.json is `@nuxt/bridge": "npm:@nuxt/bridge-edge`
> 
> You can remove `yarn.lock` and run `yarn install`.

with yarn work well

**Comment by agonzalez0515** [comment] 2022-07-29 19:35
> These are package management issues and can probably be addressed by using yarn or npm overrides. In general, however, I would advise against using the (experimental) `@vueuse/head` implementation on Bridge.

hmm interesting, the [documentation](https://v3.nuxtjs.org/bridge/bridge-composition-api/#usemeta) gives `useHead` as an option. guess I'll stick with `useNuxt2Meta` then.

**Comment by max5432112345** [comment] 2022-07-30 08:17
> These are package management issues and can probably be addressed by using yarn or npm overrides. In general, however, I would advise against using the (experimental) `@vueuse/head` implementation on Bridge.

From what package to import useMeta?
Can you in example to indicate which function from which package are imported, and not  reley on auto import.

import { useMeta } from '@vueuse/head'

**Comment by danielroe** [comment] 2022-08-01 09:56
You import `useHead` from `#head` or `#imports`.

**Comment by max5432112345** [comment] 2022-08-04 09:30
> You import `useHead` from `#head` or `#imports`.

i not import it because after install it not start

**Comment by SebbeJohansson** [comment] 2022-08-06 10:38
I managed to get it to work by putting 
```
  bridge: {
    meta: true,
  },
```
in my defineNuxtConfig and then installing `@vueuse/head`.
If I didn't install `@vueuse/head` then I was getting `This dependency was not found:  * @vueuse/head in` and @danielroe suggestion did not work. Maybe his suggestion was for nuxt3 rather than bridge, because doing his suggestion does work there.

**Closed** 2022-08-06 17:55 UTC
Labels: pending triage
