### ISSUE TITLE
Uncaught SyntaxError: The requested module '/node_modules/cookie/index.js?v=f70d5086' does not provide an export named 'default'

### ISSUE THREAD

**Issue by n4an** [nuxt/bridge#45] opened 2021-12-27 11:14 UTC
### Environment

Nuxt+bridge = Uncaught SyntaxError: The requested module '/node_modules/cookie/index.js?v=f70d5086' does not provide an export named 'default'

All modules what use cookie (auth, i18n)

### Reproduction

nuxt+bridge+auth+i18n+vite

### Describe the bug

Uncaught SyntaxError: The requested module '/node_modules/cookie/index.js?v=f70d5086' does not provide an export named 'default'

**Comment by danielroe** [comment] 2022-07-04 21:56
Yes, this kind of error is caused by a dependency and usually resolved by configuring vite optimizeDeps or adding it to your `build.transpile` array.

**Closed by danielroe** 2022-07-04 21:56 UTC
Labels: pending triage
