### ISSUE TITLE
TypeError: _vm._ssrNode is not a function

### ISSUE THREAD

**Issue by szulcus** [nuxt/bridge#510] opened 2022-09-01 15:52 UTC
### Environment
Nuxt 2 with `@nuxt/bridge`. 
```
$ npx nuxi info
Nuxt CLI v3.0.0-rc.8
```

### Reproduction

Unfortunately the package is secret so I can't create a reproduction.

### Describe the bug

After moving from `@nuxtjs/composition-api` to `@nuxt/bridge`, I get the error:
```
[Vue warn]: Error in render: "TypeError: _vm._ssrNode is not a function"

found in

---> <F24Loader>
       <Pages/index.vue> at pages/index.vue
         <Nuxt>
           <.nuxt/layouts/default.vue> at .nuxt/layouts/default.vue
             <Root>
[nuxt] [request error] _vm._ssrNode is not a function
(...)
```
`<F24Loader  />` is a component from the company's npm package (written with rollup, in Vue 2) in which we keep components common to all projects. It helps to set `ssr: false` in `nuxt.config.ts` file, or wrap a component in `<client-only>`. Is there a chance that these components will also work on the server side?

**Comment by danielroe** [comment] 2022-09-01 21:33
This sounds like a Vue issue rather than with Bridge. Would you provide a minimal reproduction? 🙏

**Comment by szulcus** [comment] 2022-09-02 16:37
> This sounds like a Vue issue rather than with Bridge. Would you provide a minimal reproduction? 🙏

Hmm, on Nuxt 2 it worked. I will try to create a reproduction.

**Comment by szulcus** [comment] 2022-09-02 17:42
Preview package:
```console
cd ./package
yarn
yarn serve
```
Build package:
```console
cd ./package
yarn
yarn build
yarn pack
```
Run `nuxt2` project:
```console
cd ./nuxt2
yarn
yarn dev
```
Run `nuxt-bridge` project:
```console
cd ./nuxt-bridge
yarn
yarn dev
```
[Nuxt Bridge SSR reproduction.zip](https://github.com/nuxt/bridge/files/9480041/Nuxt.Bridge.SSR.reproduction.zip)

**Comment by szulcus** [comment] 2022-09-05 09:53
@danielroe I would have another request. Could you take a look why I don't have types for the `hello1` and` hello2` plugins in `useNuxtApp()`? I have a similar problem with Nuxt 3 (https://github.com/johnsoncodehk/volar/issues/1785)
![image](https://user-images.githubusercontent.com/48328739/188421146-36855c6b-08e1-47a3-8b3a-0a774b240188.png)


~/plugins/hello1.ts
```ts
import { defineNuxtPlugin } from '#app'

declare module '#app' {
	interface NuxtApp {
		$hello1 (msg: string): string
	}
}

declare module '@vue/runtime-core' {
	interface ComponentCustomProperties {
		$hello1 (msg: string): string
	}
}

export default defineNuxtPlugin(({ provide }) => {
	provide('hello1', (msg: string) => `Hello 1 ${msg}!`)
});
```
~/plugins/hello2.ts
```ts
import { defineNuxtPlugin } from '#app'

declare module '#app' {
	interface NuxtApp {
		$hello2 (msg: string): string
	}
}

declare module '@vue/runtime-core' {
	interface ComponentCustomProperties {
		$hello2 (msg: string): string
	}
}

export default defineNuxtPlugin(({ provide }) => {
	provide('hello2', (msg: string) => `Hello 2 ${msg}!`)
});
```
~/tsconfig.json
```json
{
	"extends": "./.nuxt/tsconfig.json",
	"compilerOptions": {
		"target": "ES2018",
		"module": "ESNext",
		"moduleResolution": "Node",
		"lib": [
			"ESNext",
			"ESNext.AsyncIterable",
			"DOM"
		],
		"esModuleInterop": true,
		"allowJs": true,
		"sourceMap": true,
		"strict": true,
		"noEmit": true,
		"experimentalDecorators": true,
		"jsx": "preserve",
		"baseUrl": ".",
		"types": [
			"@nuxt/types",
			"@types/node",
			"@vue/runtime-core"
		]
	},
	"exclude": [
		"node_modules",
		".nuxt",
		"dist"
	]
}
```

Reproduction:
[Nuxt Bridge useNuxtApp() reproduction.zip](https://github.com/nuxt/bridge/files/9488768/Nuxt.Bridge.useNuxtAp.reproduction.zip)

```console
yarn
yarn dev
```

**Comment by MartinX3** [comment] 2022-09-05 13:29
It also started breaking for me as well

```
 husky install && nuxi prepare

husky - Git hooks installed
Nuxi 3.0.0-rc.9                                                                                                                                                             15:28:22

 FATAL  nuxtCtx.tryUse is not a function                                                                                                                                    15:28:25

  at ModuleContainer.<anonymous> (node_modules/@nuxt/bridge/module.cjs:31:17)
  at async ModuleContainer.addModule (node_modules/@nuxt/core-edge/dist/core.js:174:20)
  at async ModuleContainer.ready (node_modules/@nuxt/core-edge/dist/core.js:45:7)
  at async Nuxt._init (node_modules/@nuxt/core-edge/dist/core.js:346:5)


 ERROR  nuxtCtx.tryUse is not a function                                                                                                                                    15:28:25

  at ModuleContainer.<anonymous> (node_modules/@nuxt/bridge/module.cjs:31:17)
  at async ModuleContainer.addModule (node_modules/@nuxt/core-edge/dist/core.js:174:20)
  at async ModuleContainer.ready (node_modules/@nuxt/core-edge/dist/core.js:45:7)
  at async Nuxt._init (node_modules/@nuxt/core-edge/dist/core.js:346:5)
```

**Comment by MartinX3** [comment] 2022-09-05 13:36
It also started breaking for me as well

```
nuxi dev
Nuxi 3.0.0-rc.9                                                                                                                                                                15:35:30
Nuxt 2.16.0-27616340.013f051b                                                                                                                                                  15:35:30
                                                                                                                                                                               15:35:33
  > Local:    http://localhost:3000/ 
  > Network:  http://192.168.147.59:3000/
  > Network:  http://192.168.147.32:3000/
  > Network:  http://192.168.147.60:3000/
  > Network:  http://192.168.147.76:3000/


 FATAL  nuxtCtx.tryUse is not a function                                                                                                                                       15:35:33

  at ModuleContainer.<anonymous> (node_modules/@nuxt/bridge/module.cjs:31:17)
  at async ModuleContainer.addModule (node_modules/@nuxt/core-edge/dist/core.js:174:20)
  at async ModuleContainer.ready (node_modules/@nuxt/core-edge/dist/core.js:45:7)
  at async Nuxt._init (node_modules/@nuxt/core-edge/dist/core.js:346:5)


 ERROR  Cannot start nuxt:  nuxtCtx.tryUse is not a function                                                                                                                   15:35:33

  at ModuleContainer.<anonymous> (node_modules/@nuxt/bridge/module.cjs:31:17)
  at async ModuleContainer.addModule (node_modules/@nuxt/core-edge/dist/core.js:174:20)
  at async ModuleContainer.ready (node_modules/@nuxt/core-edge/dist/core.js:45:7)
  at async Nuxt._init (node_modules/@nuxt/core-edge/dist/core.js:346:5)
```

**Comment by MartinX3** [comment] 2022-09-05 13:36
It also started breaking for me as well

```
nuxi dev
Nuxi 3.0.0-rc.9                                                                                                                                                                15:35:30
Nuxt 2.16.0-27616340.013f051b                                                                                                                                                  15:35:30
                                                                                                                                                                               15:35:33
 FATAL  nuxtCtx.tryUse is not a function                                                                                                                                       15:35:33

  at ModuleContainer.<anonymous> (node_modules/@nuxt/bridge/module.cjs:31:17)
  at async ModuleContainer.addModule (node_modules/@nuxt/core-edge/dist/core.js:174:20)
  at async ModuleContainer.ready (node_modules/@nuxt/core-edge/dist/core.js:45:7)
  at async Nuxt._init (node_modules/@nuxt/core-edge/dist/core.js:346:5)


 ERROR  Cannot start nuxt:  nuxtCtx.tryUse is not a function                                                                                                                   15:35:33

  at ModuleContainer.<anonymous> (node_modules/@nuxt/bridge/module.cjs:31:17)
  at async ModuleContainer.addModule (node_modules/@nuxt/core-edge/dist/core.js:174:20)
  at async ModuleContainer.ready (node_modules/@nuxt/core-edge/dist/core.js:45:7)
  at async Nuxt._init (node_modules/@nuxt/core-edge/dist/core.js:346:5)
```

**Comment by danielroe** [comment] 2022-09-05 13:43
@MartinX3 That indicates an old version of `unctx`. You can run `yarn upgrade unctx` or otherwise upgrade your lockfile.

**Comment by MartinX3** [comment] 2022-09-05 13:46
@danielroe I already removed the lock file and it uses `unctx` v2.0.2 :(

**Comment by speery4** [comment] 2022-10-21 12:23
I am able to reproduce this by creating a new Nuxt 2 project and then following the Nuxt Bridge upgrade guide. The only package I have added is the `nuxt-property-decorator` package.

https://v3.nuxtjs.org/bridge/overview/

**Comment by tanBeehexa** [comment] 2022-12-08 03:46
After replace `nuxt-property-decorator` --> `vue-class-component` + `vue-property-decorator` --> Fixed

**Comment by danielroe** [comment] 2022-12-08 09:20
This sounds like it might be an issue with https://github.com/nuxt-community/nuxt-property-decorator in that case.

**Comment by Laruxo** [comment] 2022-12-20 19:39
The main contributor of `nuxt-property-decorator` has written that he does not plan to upgrade the lib for Nuxt 3 support. Apparently, he switched multiple projects to Nuxt 3 by migrating to composition API.
https://github.com/nuxt-community/nuxt-property-decorator/issues/83#issuecomment-1246615441

**Comment by MartinX3** [comment] 2022-12-20 19:54
@Laruxo it's deprecated by the composition api since vue 2.7.

**Comment by wattanx** [comment] 2024-01-06 07:29
It has not responded for a while, so I am closing it.
Reopen is welcome.
(It would be helpful if you could provide a reproduction)

**Closed by wattanx** 2024-01-06 07:29 UTC
Labels: pending triage, workaround available
